casual_responses = {
    "hi": ["Hey there!", "Hi! How can I help you today?", "Greetings!"],
    "hey": ["Heyy captain!", "Hi! How can I help you today?", "Greetings!"],
    "okay": ["Great!"],
    "got it": ["Let's go captain!! Want to learn more?", "Yessirr!! Jump to the next topic?"],
    "hello": ["Hello hello", "Yo!", "What's up!"],
    "good morning": ["Good morning! Hope you're feeling great today!"],
    "good afternoon": ["Good afternoon! What's up?"],
    "good evening": ["Evening! How can I assist you tonight?"],
    "good night": ["Good night! Take care"],
    "thanks": ["You're welcome!", "No problem!", "Anytime!"],
    "thank you": ["You're welcome!", "Glad to help!"],
    "bye": ["Goodbye!", "Take care!", "See you soon!"],
    "how are you": [
        "I'm doing great! Ready to help you.",
        "All systems go!",
        "I'm functioning normally.",
        "Doing fine. Ready to assist.",
        "All good on my side."
    ],
    "who are you": ["I'm Dion, your friendly ISRO chatbot!"],
    "what can you do": ["I can answer questions about ISRO, satellites, missions, and more!"],
    "yo": ["Yo yo!", "What's poppin'?"],
    "sup": ["Not much, just orbiting your queries 🚀"],
    "ok": ["Alright.", "Okay then.", "Got it."],
    "hmm": ["Hmm.", "Interesting.", "Thinking about it?"],
    "hmmm": ["Still thinking?", "Alright.", "Hmm, okay."],
    "hmmmmm": ["That's a long hmm.", "Deep in thought?", "Alright then."],
    "done": ["Nice, that's done.", "Good work.", "Task completed."],
    "what else": ["You tell me.", "Ready for the next?", "Want more info?"],
    "what is ur name": ["My name is Orbyx.", "You can call me Orbyx AI.", "Orbyx — that's me."],
    "can i name you": ["Sure, go ahead.", "What would you like to call me?", "I'm listening."],
    "wassup": ["Nothing much.", "Just here if you need something.", "Standing by."],
    "fine": ["Good to hear.", "Alright then.", "Nice."],
    "cool": ["Cool.", "Sounds good.", "Got it."],
    "nice": ["Glad you think so.", "Thanks.", "Alright."],
    "yeah": ["Okay.", "Gotcha.", "Understood."],
    "yes": ["Alright.", "Okay then.", "Got it."],
    "no": ["Okay, no worries.", "Got it.", "Alright then."],
    "nope": ["Noted.", "Cool.", "Alright."],
    "maybe": ["Let me know when you're sure.", "Fair enough.", "Okay."],
    "sure": ["Sure thing.", "Alright.", "Gotcha."],
    "alright": ["Okay then.", "Cool.", "Let’s move on."],
    "not sure": ["No problem.", "Take your time.", "We can figure it out."],
    "wait": ["Sure, take your time.", "Alright, waiting.", "Let me know when you're ready."],
    "idk": ["That's okay.", "We'll work it out.", "No problem."],
    "i don't know": ["All good.", "We’ll get there.", "That’s fine."],
    "maybe later": ["Sure, anytime.", "I'll be here.", "No rush."],
    "okay then": ["Okay.", "Got it.", "Understood."],
    "i'm back": ["Welcome back.", "There you are.", "Let’s continue."],
    "back": ["Welcome back.", "You're here again.", "Let’s pick up where we left off."],
    "wait a sec": ["Alright.", "Waiting.", "Let me know when you're ready."],
    "what now": ["We can continue, or ask me anything.", "That’s up to you.", "You lead, I follow."],
    "can you help me": ["Absolutely.", "That’s what I’m here for.", "Just ask away."],
    "are you there": ["Yep, still here.", "Right here.", "All ears."],
    "hello again": ["Hey again.", "Nice to see you back.", "Let’s go."]
}
